[query]
usuarioById = "SELECT id, nome, dataNascimento, email, senha FROM usuario WHERE id = %s"
usuarioByEmailSenha = "SELECT id, nome, dataNascimento, email, senha FROM usuario WHERE email = %s AND senha = %s"
quadroById = "SELECT id, nome, descricao, dono, publico FROM quadro WHERE id = %s"
quadroPublico = """WITH ultima_mensagem AS (
    SELECT m.*, 
    ROW_NUMBER() OVER (PARTITION BY m.idQuadro ORDER BY m.dataHora DESC) AS row_num
    FROM mensagem m
    )
    SELECT Q.id, Q.nome, Q.descricao, Q.dono, Q.publico, um.dataHora, um.icone, um.titulo 
    FROM quadro Q                                 
    LEFT JOIN ultima_mensagem um ON Q.id = um.idQuadro AND um.row_num = 1
    WHERE publico = TRUE"""
quadroAdmin = """WITH ultima_mensagem AS (
    SELECT m.*,
    ROW_NUMBER() OVER (PARTITION BY m.idQuadro ORDER BY m.dataHora DESC) AS row_num
    FROM mensagem m
    )
    SELECT Q.id, Q.nome, Q.descricao, Q.dono, Q.publico, um.dataHora, um.icone, um.titulo
    FROM quadro Q
    LEFT JOIN ultima_mensagem um ON Q.id = um.idQuadro AND um.row_num = 1"""
quadroUsuario = """WITH ultima_mensagem AS (
    SELECT m.*,
    ROW_NUMBER() OVER (PARTITION BY m.idQuadro ORDER BY m.dataHora DESC) AS row_num
    FROM mensagem m
)
SELECT DISTINCT
    q.id,
    q.nome,
    q.descricao,
    q.dono,
    q.publico,
    um.dataHora,
    um.icone,
    um.titulo
FROM quadro q
LEFT JOIN membrosQuadro mq ON q.id = mq.idQuadro AND mq.aprovado = TRUE
LEFT JOIN ultima_mensagem um ON q.id = um.idQuadro AND um.row_num = 1
WHERE
    q.dono = %s
    OR mq.idUsuario = %s
    OR q.publico = TRUE
"""
mensagem="SELECT * from mensagem where id = %s"
mensagemComReacoes="""SELECT m.*, ua.nome, r.*, u.nome from mensagem m
                        INNER JOIN reacao r
                            on  m.id = r.idMensagem
                                INNER JOIN usuario ua
                                    on m.idUsuario = ua.id
                                INNER JOIN usuario u
                                    on r.idUsuario = u.id
                        where m.id = %s
                        order by r.dataHora desc
                    """
mensagensDesc = """SELECT m.*, u.nome
                    FROM mensagem m INNER JOIN usuario u
                        on m.idUsuario = u.id
                    WHERE m.idQuadro = %s
                        AND m.id <= %s
                    ORDER BY id DESC
                    LIMIT %s;"""
