[query]
usuarioById = """SELECT u.id, u.nome, u.dataNascimento, u.email, u.senha,
                    EXISTS (
                                       SELECT 1 FROM administradores a WHERE a.idUsuario = u.id
                                       ) AS ehAdmin
                    FROM usuario u WHERE id = %s;"""

usuarioByEmailSenha = """SELECT u.id, u.nome, u.dataNascimento, u.email, u.senha,
                                    EXISTS (
                                       SELECT 1 FROM administradores a WHERE a.idUsuario = u.id
                                    ) AS ehAdmin
                        FROM usuario u WHERE u.email = %s AND u.senha = %s"""
quadroById = """
                SELECT
                    quadro.id,
                    quadro.nome,
                    quadro.descricao,
                    quadro.dono,
                    quadro.publico,
                    COUNT(mensagem.id) AS qtde_mensagens
                FROM
                    quadro
                LEFT JOIN
                    mensagem ON mensagem.idQuadro = quadro.id
                WHERE
                    quadro.id = %s
                GROUP BY
                    quadro.id, quadro.nome, quadro.descricao, quadro.dono, quadro.publico;
            """
quadroPublico = """WITH ultima_mensagem AS (
    SELECT m.*, 
    ROW_NUMBER() OVER (PARTITION BY m.idQuadro ORDER BY m.dataHora DESC) AS row_num
    FROM mensagem m
    )
    SELECT Q.id, Q.nome, Q.descricao, Q.dono, Q.publico, um.dataHora, um.icone, um.titulo 
    FROM quadro Q                                 
    LEFT JOIN ultima_mensagem um ON Q.id = um.idQuadro AND um.row_num = 1
    WHERE publico = TRUE"""
quadroAdmin = """WITH ultima_mensagem AS (
    SELECT m.*,
    ROW_NUMBER() OVER (PARTITION BY m.idQuadro ORDER BY m.dataHora DESC) AS row_num
    FROM mensagem m
    )
    SELECT Q.id, Q.nome, Q.descricao, Q.dono, Q.publico, um.dataHora, um.icone, um.titulo
    FROM quadro Q
    LEFT JOIN ultima_mensagem um ON Q.id = um.idQuadro AND um.row_num = 1"""
quadroUsuario = """WITH last_message AS (
    SELECT m.*,
           ROW_NUMBER() OVER (PARTITION BY m.idQuadro ORDER BY m.dataHora DESC) AS rn
    FROM mensagem m
)
SELECT q.id,
       q.nome,
       q.descricao,
       q.dono,
       q.publico,
       lm.dataHora,
       lm.icone,
       lm.titulo
FROM quadro q
LEFT JOIN last_message lm ON q.id = lm.idQuadro AND lm.rn = 1
WHERE q.dono = %s
   OR EXISTS (
       SELECT 1
       FROM membrosQuadro mq
       WHERE mq.idQuadro = q.id
         AND (mq.idUsuario = %s
         AND mq.aprovado = TRUE)
         OR q.publico = TRUE
   );
"""
mensagem="""
        SELECT m.*, u.nome from mensagem m
            INNER JOIN usuario u
                ON m.idUsuario = u.id
            where m.id = %s
        """
reacoes="""
          select r.*, u.nome
                from reacao r inner join usuario u
                    on r.idusuario = u.id
                where r.idmensagem = %s;
"""
mensagemComReacoes="""SELECT m.*, ua.nome, r.*, u.nome from mensagem m
                        INNER JOIN reacao r
                            on  m.id = r.idMensagem
                                INNER JOIN usuario ua
                                    on m.idUsuario = ua.id
                                INNER JOIN usuario u
                                    on r.idUsuario = u.id
                        where m.id = %s
                        order by r.dataHora desc
                    """
mensagensDesc = """SELECT m.*, u.nome
                        FROM mensagem m
                            INNER JOIN usuario u ON m.idUsuario = u.id
                        WHERE m.idQuadro = %s
                        ORDER BY m.dataHora DESC, m.id DESC
                        LIMIT %s OFFSET %s;
                """
upsertReacaoMensagem = """
                    INSERT INTO reacao (dataHora, idMensagem, idUsuario, tipo)
                    VALUES (%s, %s, %s, %s)
                    ON CONFLICT (idMensagem, idUsuario)
                    DO UPDATE SET
                        tipo = EXCLUDED.tipo,
                        dataHora = EXCLUDED.dataHora;
                        """
validarAcessoUsuario = """
                        -- Parametros: idQuadro, idQuadro, idQuadro, idUsuario
                        SELECT
                            u.nome,
                            EXISTS (
                                SELECT 1 FROM administradores a WHERE a.idUsuario = u.id
                            ) AS eh_administrador,
                            EXISTS (
                                SELECT 1 FROM quadro q WHERE q.id = %s AND q.dono = u.id
                            ) AS eh_dono_do_quadro,
                            EXISTS (
                                SELECT 1 FROM membrosQuadro mq WHERE mq.idUsuario = u.id  AND mq.aprovado = TRUE AND mq.idQuadro = %s
                            ) AS eh_membro_do_quadro,
                            EXISTS (
                                SELECT 1 FROM quadro q WHERE q.id = %s AND q.publico = TRUE
                            ) as eh_publico
                        FROM
                            usuario u
                        WHERE
                            u.id = %s;
                    """
cadastrarMensagem = """
                    INSERT INTO mensagem (idQuadro, idUsuario, dataHora, titulo, texto, anexo, expiraEm, icone) VALUES
                    (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING id;
                    """
criarQuadro = """
                INSERT INTO quadro (nome, descricao, dono, publico) VALUES
                    (%s, %s, %s, %s);
                """
listarFiltrarQuadros = """
                SELECT Q.*, U.nome from quadro Q
                    INNER JOIN usuario U
                        on U.id = Q.dono
                    WHERE Q.nome ILIKE %s
                    ORDER BY Q.nome;
                """
cadastrarUsuario = """
                    INSERT INTO usuario (nome, dataNascimento, email, senha) VALUES
                    (%s, %s, %s, %s) RETURNING id;
                    """
atualizarUsuario = """
                    UPDATE USUARIO SET nome = %s, dataNascimento = %s, email = %s, senha = %s
                        WHERE id = %s;
                    """
deletarUsuario = """
                    DELETE FROM usuario WHERE id = %s;
                    """
listarFiltrarUsuarios = """
                SELECT * FROM usuario
                    WHERE nome ILIKE %s
                    ORDER BY nome;
                """
inserirMembroQuadro = """
                INSERT INTO membrosQuadro (idQuadro, idUsuario, aprovado) VALUES
                    (%s, %s, false);
                """
removerMembroQuadro = """
                DELETE FROM membrosQuadro
                    WHERE idQuadro = %s
                        AND idUsuario = %s;
"""
listarMembrosQuadro = """
                SELECT mq.*, u.nome FROM membrosQuadro mq
                    INNER JOIN usuario u
                        ON mq.idUsuario = u.id
                    WHERE idQuadro = %s
                    ORDER BY mq.aprovado ASC, u.nome ASC;
                """
aprovarMembroQuadro = """
                UPDATE membrosQuadro
                    SET aprovado = True
                    WHERE idQuadro = %s AND idUsuario = %s;
                """
deletarMensagem = """
                DELETE from mensagem
                    WHERE id = %s;
                """
usuarioComAdmin = """
SELECT u.*,EXISTS (
                   SELECT 1 FROM administradores a WHERE a.idUsuario = u.id
                   ) AS eh_administrador
       FROM usuario u
       WHERE u.id = %s;
"""

